question_data = [
    {"question": "The Great Wall of China is visible from space.", "answer": "False", "explanation": "It is very narrow and generally not visible to the naked eye from orbit."},
    {"question": "The capital of Australia is Sydney.", "answer": "False", "explanation": "The capital of Australia is Canberra."},
    {"question": "There are 365 days in a leap year.", "answer": "False", "explanation": "Leap years contain 366 days."},
    {"question": "The human body has four lungs.", "answer": "False", "explanation": "Humans have two lungs."},
    {"question": "Lightning never strikes the same place twice.", "answer": "False", "explanation": "Lightning can strike the same location multiple times."},
    {"question": "Goldfish have a memory span of only three seconds.", "answer": "False", "explanation": "Goldfish can remember information for months."},
    {"question": "The tallest mountain on Earth is Mount Everest.", "answer": "True", "explanation": "Mount Everest is the highest mountain above sea level."},
    {"question": "Bananas grow on trees.", "answer": "False", "explanation": "Banana plants are large herbs, not trees."},
    {"question": "Sharks are mammals.", "answer": "False", "explanation": "Sharks are fish."},
    {"question": "The human skeleton is made up of over 200 bones.", "answer": "True", "explanation": "An adult human has 206 bones."},
    {"question": "The currency of Japan is the Yen.", "answer": "True", "explanation": "Japan’s official currency is the yen."},
    {"question": "The sun is a planet.", "answer": "False", "explanation": "The Sun is a star."},
    {"question": "Water boils at 100 degrees Celsius at sea level.", "answer": "True", "explanation": "At standard atmospheric pressure, water boils at 100°C."},
    {"question": "Penguins can fly.", "answer": "False", "explanation": "Penguins are flightless birds adapted for swimming."},
    {"question": "The human heart has four chambers.", "answer": "True", "explanation": "It has two atria and two ventricles."},
    {"question": "The Eiffel Tower is located in Berlin.", "answer": "False", "explanation": "The Eiffel Tower is located in Paris, France."},
    {"question": "Sound travels faster than light.", "answer": "False", "explanation": "Light travels much faster than sound."},
    {"question": "The Pacific Ocean is the largest ocean on Earth.", "answer": "True", "explanation": "It covers more surface area than any other ocean."},
    {"question": "Humans have five senses.", "answer": "False", "explanation": "Humans have more than five senses, including balance and temperature."},
    {"question": "The Mona Lisa was painted by Vincent van Gogh.", "answer": "False", "explanation": "It was painted by Leonardo da Vinci."},
    {"question": "The Earth revolves around the Sun.", "answer": "True", "explanation": "Earth orbits the Sun once every year."},
    {"question": "All insects have six legs.", "answer": "True", "explanation": "Six legs are a defining feature of insects."},
    {"question": "Diamonds are made of compressed coal.", "answer": "False", "explanation": "Diamonds form from pure carbon deep in Earth’s mantle."},
    {"question": "Humans share about 98% of their DNA with chimpanzees.", "answer": "True", "explanation": "Humans and chimpanzees have highly similar DNA."},
    {"question": "Venus is the hottest planet in our solar system.", "answer": "True", "explanation": "Its thick atmosphere traps heat through a greenhouse effect."},
    {"question": "Bats are blind.", "answer": "False", "explanation": "Bats can see and also use echolocation."},
    {"question": "Oxygen is the most abundant gas in Earth’s atmosphere.", "answer": "False", "explanation": "Nitrogen makes up about 78% of Earth’s atmosphere."},
    {"question": "Water is an element.", "answer": "False", "explanation": "Water is a compound made of hydrogen and oxygen."},
    {"question": "Lightning is hotter than the surface of the sun.", "answer": "True", "explanation": "Lightning can reach temperatures hotter than the Sun’s surface."},
    {"question": "Sound cannot travel through a vacuum.", "answer": "True", "explanation": "Sound requires a medium like air or water to travel."},
    {"question": "Plants get their energy from soil.", "answer": "False", "explanation": "Plants get energy from sunlight through photosynthesis."},
    {"question": "The chemical symbol for gold is Au.", "answer": "True", "explanation": "Au comes from the Latin word 'aurum'."},
    {"question": "Fungi are a type of plant.", "answer": "False", "explanation": "Fungi belong to their own biological kingdom."},
    {"question": "Whales are fish.", "answer": "False", "explanation": "Whales are mammals."},
    {"question": "The human brain uses only 10% of its capacity.", "answer": "False", "explanation": "Humans use all parts of the brain over time."},
    {"question": "Lizards can regenerate lost tails.", "answer": "True", "explanation": "Many lizard species can regrow their tails."},
    {"question": "Blood in your veins is blue.", "answer": "False", "explanation": "Blood is always red; veins appear blue due to light."},
    {"question": "Mars has two moons.", "answer": "True", "explanation": "Mars has two moons: Phobos and Deimos."},
    {"question": "Trees release oxygen only during the day.", "answer": "True", "explanation": "Photosynthesis occurs in sunlight."},
    {"question": "Some turtles can breathe through their butts.", "answer": "True", "explanation": "Certain turtle species use cloacal respiration."},
    {"question": "The Roman Empire fell in 476 AD.", "answer": "True", "explanation": "476 AD marks the fall of the Western Roman Empire."},
    {"question": "The Great Fire of London happened in 1666.", "answer": "True", "explanation": "The fire devastated London in 1666."},
    {"question": "Cleopatra was Egyptian by ancestry.", "answer": "False", "explanation": "She was of Greek Macedonian descent."},
    {"question": "Leonardo da Vinci painted The Starry Night.", "answer": "False", "explanation": "The Starry Night was painted by Vincent van Gogh."},
    {"question": "The Berlin Wall fell in 1989.", "answer": "True", "explanation": "Its fall symbolized the approaching end of the Cold War."},
    {"question": "The Titanic sank on its maiden voyage.", "answer": "True", "explanation": "It sank in 1912 during its first trip."},
    {"question": "The Cold War was a direct military conflict between the US and the Soviet Union.", "answer": "False", "explanation": "It was mainly political tension and proxy conflicts."},
    {"question": "The Eiffel Tower was originally built as a temporary structure.", "answer": "True", "explanation": "It was initially intended to stand for 20 years."},
    {"question": "Joan of Arc was executed for heresy.", "answer": "True", "explanation": "She was executed in 1431."},
    {"question": "World War II ended in 1945.", "answer": "True", "explanation": "Germany and Japan surrendered in 1945."},
    {"question": "The Magna Carta was signed in 1512.", "answer": "False", "explanation": "It was signed in 1215."},
    {"question": "The Statue of Liberty was a gift from France.", "answer": "True", "explanation": "France gifted it to the United States in 1886."},
    {"question": "Albert Einstein won a Nobel Prize for the theory of relativity.", "answer": "False", "explanation": "He won for his explanation of the photoelectric effect."},
    {"question": "The Colosseum in Rome was used for naval battles.", "answer": "True", "explanation": "Early events may have included staged water spectacles."},
    {"question": "Shakespeare wrote over 100 plays.", "answer": "False", "explanation": "He wrote around 39 plays."},
    {"question": "The Great Pyramid of Giza is the oldest of the Seven Wonders of the Ancient World.", "answer": "True", "explanation": "It is the only ancient wonder still standing."},
    {"question": "Genghis Khan ruled over the largest contiguous land empire in history.", "answer": "True", "explanation": "His empire stretched across Asia and Europe."},
    {"question": "The Black Death occurred in the 14th century.", "answer": "True", "explanation": "It peaked in the mid-1300s."},
    {"question": "Napoleon was born in France.", "answer": "True", "explanation": "He was born in Corsica after it became French territory."},
    {"question": "The Rosetta Stone helped decode ancient Mayan writing.", "answer": "False", "explanation": "It helped decode Egyptian hieroglyphs."},
    {"question": "The Beatles were originally a five-member band.", "answer": "False", "explanation": "The famous lineup consisted of four members."},
    {"question": "The TV series Friends was set in Chicago.", "answer": "False", "explanation": "It was set in New York City."},
    {"question": "Walt Disney was cryogenically frozen after his death.", "answer": "False", "explanation": "That is a popular myth."},
    {"question": "The first Harry Potter book was published in the 1990s.", "answer": "True", "explanation": "It was first published in 1997."},
    {"question": "Leonardo DiCaprio has never won an Academy Award.", "answer": "False", "explanation": "He won Best Actor in 2016."},
    {"question": "The video game Minecraft was created in Sweden.", "answer": "True", "explanation": "It was developed by the Swedish company Mojang."},
    {"question": "Elvis Presley only ever performed outside the U.S. once.", "answer": "True", "explanation": "He performed in Canada."},
    {"question": "The Marvel superhero Thor is based on a Norse god.", "answer": "True", "explanation": "Thor originates from Norse mythology."},
    {"question": "The Simpsons is the longest-running scripted TV show in the U.S.", "answer": "True", "explanation": "It has been airing since 1989."},
    {"question": "The Mona Lisa is displayed in the British Museum.", "answer": "False", "explanation": "It is displayed in the Louvre in Paris."},
    {"question": "Taylor Swift’s debut album was released in 2006.", "answer": "True", "explanation": "Her self-titled debut album was released in 2006."},
    {"question": "James Cameron directed The Lord of the Rings trilogy.", "answer": "False", "explanation": "The trilogy was directed by Peter Jackson."},
    {"question": "Oprah Winfrey’s talk show ended in 2011.", "answer": "True", "explanation": "The show concluded after 25 years in 2011."},
    {"question": "“Let It Go” is a song from Moana.", "answer": "False", "explanation": "It is a song from the movie Frozen."},
    {"question": "Netflix started as a DVD rental service.", "answer": "True", "explanation": "It began by mailing DVDs to customers."},
    {"question": "There are more Star Wars movies than Harry Potter movies.", "answer": "False", "explanation": "The main Harry Potter series has 8 films."},
    {"question": "The original Pac-Man game was released in the 1980s.", "answer": "True", "explanation": "Pac-Man was first released in 1980."},
    {"question": "Beyoncé was once part of a group called TLC.", "answer": "False", "explanation": "She was a member of Destiny’s Child."},
    {"question": "J.K. Rowling wrote books under a different name.", "answer": "True", "explanation": "She also writes under the name Robert Galbraith."},
    {"question": "The first YouTube video was uploaded in 2005.", "answer": "True", "explanation": "It was uploaded in April 2005."},
    {"question": "Mount Kilimanjaro is located in Kenya.", "answer": "False", "explanation": "It is located in Tanzania."},
    {"question": "The Amazon River is the longest river in the world.", "answer": "False", "explanation": "The Nile is generally considered longer."},
    {"question": "Russia is the largest country by land area.", "answer": "True", "explanation": "It spans Eastern Europe and northern Asia."},
    {"question": "Tokyo is the most populous city in the world.", "answer": "True", "explanation": "The Greater Tokyo area has the largest metropolitan population."},
    {"question": "There are 52 states in the United States.", "answer": "False", "explanation": "The United States has 50 states."},
    {"question": "The Sahara is the largest desert in the world.", "answer": "False", "explanation": "Antarctica is the largest desert overall."},
    {"question": "Australia is both a country and a continent.", "answer": "True", "explanation": "Australia is classified as both."},
    {"question": "Canada’s official languages are English and French.", "answer": "True", "explanation": "Both languages are officially recognized at the federal level."},
    {"question": "“Bonjour” means “thank you” in French.", "answer": "False", "explanation": "It means 'hello' in French."},
    {"question": "The Great Barrier Reef is located off the coast of Australia.", "answer": "True", "explanation": "It lies off the coast of Queensland, Australia."},
    {"question": "Spanish is the most spoken language in the world.", "answer": "False", "explanation": "Mandarin Chinese has the most native speakers."},
    {"question": "Earth is the only planet in our solar system with liquid water on the surface.", "answer": "True", "explanation": "It is the only known planet with stable surface liquid water."},
    {"question": "The Leaning Tower of Pisa was built to lean.", "answer": "False", "explanation": "It leans due to unstable ground during construction."},
    {"question": "The currency of the UK is the Euro.", "answer": "False", "explanation": "The UK uses the Pound Sterling."},
    {"question": "You can see the Northern Lights in Iceland.", "answer": "True", "explanation": "Iceland is a popular location to see the aurora borealis."},
    {"question": "Mount Everest lies on the border of Nepal and China.", "answer": "True", "explanation": "It straddles the border between Nepal and China."},
    {"question": "Koalas are bears.", "answer": "False", "explanation": "Koalas are marsupials, not bears."},
    {"question": "Daylight saving time is practiced worldwide.", "answer": "False", "explanation": "Many countries do not observe daylight saving time."},
    {"question": "An octopus has three hearts.", "answer": "True", "explanation": "Two pump blood to the gills and one to the rest of the body."},
    {"question": "There are 1000 meters in a kilometer.", "answer": "True", "explanation": "That is the metric definition of a kilometer."}
]